from typing import Any
from typing import Optional

from .ucre import build_re as build_re

RE_TYPE: Any

class SchemaError(Exception):
    def __init__(self, name: Any, val: Any) -> None: ...

class Match:
    schema: Any = ...
    index: Any = ...
    last_index: Any = ...
    raw: Any = ...
    text: Any = ...
    url: Any = ...
    def __init__(self, linkifyit: Any, shift: Any) -> None: ...

class LinkifyIt:
    default_options: Any = ...
    default_schemas: Any = ...
    tlds_2ch_src_re: str = ...
    tlds_default: Any = ...
    re: Any = ...
    def __init__(
        self, schemas: Optional[Any] = ..., options: Optional[Any] = ...
    ) -> None: ...
    def add(self, schema: Any, definition: Any): ...
    def set(self, options: Any): ...
    def test(self, text: Any): ...
    def pretest(self, text: Any): ...
    def test_schema_at(self, text: Any, name: Any, position: Any): ...
    def match(self, text: Any): ...
    def tlds(self, list_tlds: Any, keep_old: bool = ...): ...
    def normalize(self, match: Any) -> None: ...
