from typing import Any

from .ucre import build_re as build_re

RE_TYPE: Any

class SchemaError(Exception):
    def __init__(self, name, val) -> None: ...

class Match:
    schema: Any
    index: Any
    last_index: Any
    raw: Any
    text: Any
    url: Any
    def __init__(self, linkifyit, shift) -> None: ...

class LinkifyIt:
    default_options: Any
    default_schemas: Any
    tlds_2ch_src_re: str
    tlds_default: Any
    re: Any
    def __init__(
        self, schemas: Any | None = ..., options: Any | None = ...
    ) -> None: ...
    def add(self, schema, definition): ...
    def set(self, options): ...
    def test(self, text): ...
    def pretest(self, text): ...
    def test_schema_at(self, text, name, position): ...
    def match(self, text): ...
    def match_at_start(self, text): ...
    def tlds(self, list_tlds, keep_old: bool = ...): ...
    def normalize(self, match) -> None: ...
