from typing import Any

from pure_protobuf.dataclasses_ import field as field
from pure_protobuf.dataclasses_ import message as message
from pure_protobuf.types import int32 as int32
from pure_protobuf.types import int64 as int64

class TimeSpan:
    seconds: int64 = ...
    nanos: int32 = ...
    def __init__(self, seconds: Any, nanos: Any) -> None: ...

class Timestamp(TimeSpan):
    def __init__(self, seconds: Any, nanos: Any) -> None: ...

class Duration(TimeSpan):
    def __init__(self, seconds: Any, nanos: Any) -> None: ...

class Any_:
    type_url: str = ...
    value: bytes = ...
    def __init__(self, type_url: Any, value: Any) -> None: ...
