from typing import Any

def emojize(
    string,
    delimiters=...,
    variant: Any | None = ...,
    language: str = ...,
    version: Any | None = ...,
    handle_version: Any | None = ...,
): ...
def demojize(
    string,
    delimiters=...,
    language: str = ...,
    version: Any | None = ...,
    handle_version: Any | None = ...,
): ...
def replace_emoji(string, replace: str = ..., version: int = ...): ...
def emoji_list(string): ...
def distinct_emoji_list(string): ...
def emoji_count(string, unique: bool = ...): ...
def is_emoji(string): ...
def version(string): ...
